# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://reikiapotemes.lt
title: Reikia Potėmes
email: lietuviuiskaita12@gmail.com
author: Potemės
description: > # "Write an awesome description for your new site here. 
  Rašome 10 klasės PUPP ir 12 klasės VBE potemių kalbėjimus. Kiekvienam klientui skiriame individualų dėmesį!
copyright: 'Copyright &copy; 2015 ReikiaPotemes.lt All Rights Reserved.'
Sprendimas: 'Nauji VĖJAI'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: 
